### ISSUE TITLE
font list went wrong

### ISSUE THREAD

**Issue by roohix** [fzerorubigd/persian-fonts-linux#12]
It seems something wrong in list of fonts and installation goes to problem
![2](https://user-images.githubusercontent.com/9565737/70711259-b4dee980-1cfe-11ea-966b-dbd4c2abad1a.png)

![Screenshot from 2019-12-12 16-44-13](https://user-images.githubusercontent.com/9565737/70711213-9a0c7500-1cfe-11ea-804c-2486f993d53e.png)

**Comment by fzerorubigd** [comment]
I tested and the font list is ok :/ ```http://fzerorubigd.github.com/persian-fonts-linux/list```

Are you sure you are not blocked by any firewall/censorship?

**Comment by roohix** [comment]
I dont know what happend but installed successfully 
Thanks
