### ISSUE TITLE
تشکر بابت اسکریپت خوب

### ISSUE THREAD

**Issue by amirbagh75** [fzerorubigd/persian-fonts-linux#13]
من هر وقت یک os جدید نصب میکنم یکی از اسکریپت هایی که اجرا میکنم اینه. ازت متشکرم بابت این ابزار کاربردی

**Comment by fzerorubigd** [comment]
لطف دارین. ممنون. 

چون اینجا مشکلی مطرح نشده من با اجازتون این ایشو رومیبندم. 
موفق باشین :)‌
