### ISSUE TITLE
افزودن فونت‌های سری ir

### ISSUE THREAD

**Issue by khozaei** [fzerorubigd/persian-fonts-linux#14]
سلام ممنون از پروژه خوبی که ایجاد کردین، لطفا قلم‌های سری آی‌آر هم اضافه کنید.

**Comment by fzerorubigd** [comment]
اگر لیست و جایی که بشه دانلود کرد رو ارایه کنید، حتما. 

- لطفا فقط فونتهایی که رایگان در دسترسند، نه فونهتایی که رایگان نیستن.

**Comment by khozaei** [comment]
فونت‌های سری آی‌آر استاندارد شده همون فونت‌های سری بی هستند و توسط شورای عالی اطلاع رسانی تولید شده‌اند. متاسفانه سایت رسمی شورای عالی اطلاع‌رسانی در دسترس نیست ولی فونت‌های اون رو از دو سایت دیگه میشه دریافت کرد که لینک اون‌ها رو می‌ذارم.
ممنون از توجه‌تون

لینک صفحه:
[باب‌آرت](https://babart.ir/1393/12/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-39-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%A7%D8%B1%D8%AF%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B4%D8%AF%D9%87-%D8%AA/)
[ویراستاران](https://virastaran.net/abzar/124/)

لینک دانلود:
[آی‌آر فونت با فرمت رار](https://babart.ir/DL-Files/Standard%20IRFonts-babArt.ir.rar)
[آی‌آر فونت با فرمت زیپ](https://virastaran.net/wp-content/uploads/2014/01/IRFontPack-virastaran.net_.zip)

به نظر میاد چون لینک دوم زیپ هست مناسب‌تر باشه.
با تشکر
