### ISSUE TITLE
font url 404

### ISSUE THREAD

**Issue by vahidtwo** [fzerorubigd/persian-fonts-linux#18]
https://fzerorubigd.github.com/persian-fonts-linux/list not available

**Comment by esmaeelE** [comment]
Because of this page not exist, the installer script `./farsifonts.sh` return after selection of 1) All without any warning.

**Comment by vahidtwo** [comment]
it's command try to connect this page and cant to do that

**Comment by sajjads24** [comment]
hi
this is not work for me on fedora 34 !
not fond url 
i am can not download all fonts !
how fix it ?

**Comment by mortezakarimi** [comment]
@sajjads24 
> hi
> this is not work for me on fedora 34 !
> not fond url
> i am can not download all fonts !
> how fix it ?

I think you have a DNS problem, I test this URL with `curl` tools by running following command
```console
curl http://fzero.rubi.gd/persian-fonts-linux/list
```
and get the following result
```
Vazir|Vazir.zip|https://github.com/rastikerdar/vazir-font/archive/master.zip|"A Persian (Farsi) Font"|
FarsiFonts|FarsiFonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/farsifonts-0.4.zip|"Full standard fonts from farsiweb.ir(RIP) including Elham, Terafik, Terafik Bold, Titr, Roya, Roya Bold, Koodak, Nazli, Nazli Bold, and Homa"|
BFonts|bfonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/bfonts.zip|"Old school B Fonts, Originally published with Borna Rayaneh products in early 2000."|
IranianSans|irsans.zip|http://fzerorubigd.github.com/persian-fonts-linux/irsans.zip|"Iranian Sans"|
IranNastaliq|in.zip|http://fzerorubigd.github.com/persian-fonts-linux/irannastaliq.zip|"Iran nastaliq font"|
FPF|FPF.zip|http://fzerorubigd.github.com/persian-fonts-linux/fpf-1.0.0-Beta-1.zip|"Free Persian Font, Originally from source forge."|
Lalezar|Lalezar-Regular.ttf|https://github.com/BornaIz/Lalezar/raw/master/Font%20files/Lalezar-Regular.ttf|"Lalezar font"|
XBZar|XBZar.zip|http://fonts.irmug.com/Zar.zip|"XBZar From irmug.com"|
XBNilufar|XBNilufar.zip|http://fonts.irmug.com/Niloofar.zip|"XBNilufar From irmug.com"|
XBKhoramshahr|XBKhoramshahr.zip|http://fonts.irmug.com/Khoramshahr.zip|"XBKhoramshahr From irmug.com"|
XBKayhan|XBKayhan.zip|http://fonts.irmug.com/Kayhan.zip|"XBKayhan From irmug.com"|
XBYaghout|XBYaghout.zip|http://fonts.irmug.com/Yagut.zip|"XBYaghout From irmug.com"|
XBRiyaz|XBRiyaz.zip|http://fonts.irmug.com/Riyaz.zip|"XBRiyaz From irmug.com"|
XBRoya|XBRoya.zip|http://fonts.irmug.com/Roya.zip|"XBRoya From irmug.com"|
XBShafigh|XBShafigh.zip|http://fonts.irmug.com/Shafigh.zip|"XBShafigh From irmug.com"|
XBShafighKurd|XBShafighKurd.zip|http://fonts.irmug.com/Shafigh%20Kurd.zip|"XBShafighKurd From irmug.com"|
XBShafighUzbek|XBShafighUzbek.zip|http://fonts.irmug.com/Shafigh%20Uzbek.zip|"XBShafighUzbek From irmug.com"|
XBShiraz|XBShiraz.zip|http://fonts.irmug.com/Shiraz.zip|"XBShiraz From irmug.com"|
XBSols|XBSols.zip|http://fonts.irmug.com/Sols.zip|"XBSols From irmug.com"|
XBTitr|XBTitr.zip|http://fonts.irmug.com/Titre.zip|"XBTitr From irmug.com"|
XBTabriz|XBTabriz.zip|http://fonts.irmug.com/Tabriz.zip|"XBTabriz From irmug.com"|
XBTraffic|XBTraffic.zip|http://fonts.irmug.com/Traffic.zip|"XBTraffic From irmug.com"|
XBVahid|XBVahid.zip|http://fonts.irmug.com/Vahid.zip|"XBVahid From irmug.com"|
XBVosta|XBVosta.zip|http://fonts.irmug.com/Vosta.zip|"XBVosta From irmug.com"|
XBYermook|XBYermook.zip|http://fonts.irmug.com/Yermook.zip|"XBYermook From irmug.com"|
XBYas|XBYas.zip|http://fonts.irmug.com/Yas.zip|"XBYas From irmug.com"|
XBZiba|XBZiba.zip|http://fonts.irmug.com/Ziba.zip|"XBZiba From irmug.com"|
Tahoma|Tahoma.zip|http://fzerorubigd.github.com/persian-fonts-linux/tahoma.zip|"MS Tahoma, just here to completet the set :)"|
Samim|Samim.zip|https://github.com/rastikerdar/samim-font/archive/master.zip|"A Persian (Farsi) Font"|
Shabnam|Shabnam.zip|https://github.com/rastikerdar/shabnam-font/archive/master.zip|"A Persian (Farsi) Font"|
Sahel|Sahel.zip|https://github.com/rastikerdar/sahel-font/archive/master.zip|"A Persian (farsi) Font"|
VazirCode|VazirCode.zip|https://github.com/rastikerdar/vazir-code-font/archive/master.zip|"A Persian (farsi) Monospaced Font for coding"|
Tanha|Tanha.zip|https://github.com/rastikerdar/tanha-font/archive/master.zip|"Tanha, A Persian (Farsi) font"|
Nahid|Nahid.zip|https://github.com/rastikerdar/nahid-font/archive/master.zip|"Nahid, A Persian (Farsi) font"|
Parastoo|Tarastoo.zip|https://github.com/rastikerdar/parastoo-font/archive/master.zip|"Parastoo, A Persian (Farsi) font"|
RFonts|RFonts.zip|https://virastaran.net/wp-content/uploads/2014/01/IRFontPack-virastaran.net_.zip|"Fonts from I.R. Iran Supreme Council of Information and Communication Technology (SCICT)"|
```

**Comment by sajjads24** [comment]
> @sajjads24
> 
> > hi
> > this is not work for me on fedora 34 !
> > not fond url
> > i am can not download all fonts !
> > how fix it ?
> 
> I think you have a DNS problem, I test this URL with `curl` tools by running following command
> 
> ```
> curl http://fzero.rubi.gd/persian-fonts-linux/list
> ```
> 
> and get the following result
> 
> ```
> Vazir|Vazir.zip|https://github.com/rastikerdar/vazir-font/archive/master.zip|"A Persian (Farsi) Font"|
> FarsiFonts|FarsiFonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/farsifonts-0.4.zip|"Full standard fonts from farsiweb.ir(RIP) including Elham, Terafik, Terafik Bold, Titr, Roya, Roya Bold, Koodak, Nazli, Nazli Bold, and Homa"|
> BFonts|bfonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/bfonts.zip|"Old school B Fonts, Originally published with Borna Rayaneh products in early 2000."|
> IranianSans|irsans.zip|http://fzerorubigd.github.com/persian-fonts-linux/irsans.zip|"Iranian Sans"|
> IranNastaliq|in.zip|http://fzerorubigd.github.com/persian-fonts-linux/irannastaliq.zip|"Iran nastaliq font"|
> FPF|FPF.zip|http://fzerorubigd.github.com/persian-fonts-linux/fpf-1.0.0-Beta-1.zip|"Free Persian Font, Originally from source forge."|
> Lalezar|Lalezar-Regular.ttf|https://github.com/BornaIz/Lalezar/raw/master/Font%20files/Lalezar-Regular.ttf|"Lalezar font"|
> XBZar|XBZar.zip|http://fonts.irmug.com/Zar.zip|"XBZar From irmug.com"|
> XBNilufar|XBNilufar.zip|http://fonts.irmug.com/Niloofar.zip|"XBNilufar From irmug.com"|
> XBKhoramshahr|XBKhoramshahr.zip|http://fonts.irmug.com/Khoramshahr.zip|"XBKhoramshahr From irmug.com"|
> XBKayhan|XBKayhan.zip|http://fonts.irmug.com/Kayhan.zip|"XBKayhan From irmug.com"|
> XBYaghout|XBYaghout.zip|http://fonts.irmug.com/Yagut.zip|"XBYaghout From irmug.com"|
> XBRiyaz|XBRiyaz.zip|http://fonts.irmug.com/Riyaz.zip|"XBRiyaz From irmug.com"|
> XBRoya|XBRoya.zip|http://fonts.irmug.com/Roya.zip|"XBRoya From irmug.com"|
> XBShafigh|XBShafigh.zip|http://fonts.irmug.com/Shafigh.zip|"XBShafigh From irmug.com"|
> XBShafighKurd|XBShafighKurd.zip|http://fonts.irmug.com/Shafigh%20Kurd.zip|"XBShafighKurd From irmug.com"|
> XBShafighUzbek|XBShafighUzbek.zip|http://fonts.irmug.com/Shafigh%20Uzbek.zip|"XBShafighUzbek From irmug.com"|
> XBShiraz|XBShiraz.zip|http://fonts.irmug.com/Shiraz.zip|"XBShiraz From irmug.com"|
> XBSols|XBSols.zip|http://fonts.irmug.com/Sols.zip|"XBSols From irmug.com"|
> XBTitr|XBTitr.zip|http://fonts.irmug.com/Titre.zip|"XBTitr From irmug.com"|
> XBTabriz|XBTabriz.zip|http://fonts.irmug.com/Tabriz.zip|"XBTabriz From irmug.com"|
> XBTraffic|XBTraffic.zip|http://fonts.irmug.com/Traffic.zip|"XBTraffic From irmug.com"|
> XBVahid|XBVahid.zip|http://fonts.irmug.com/Vahid.zip|"XBVahid From irmug.com"|
> XBVosta|XBVosta.zip|http://fonts.irmug.com/Vosta.zip|"XBVosta From irmug.com"|
> XBYermook|XBYermook.zip|http://fonts.irmug.com/Yermook.zip|"XBYermook From irmug.com"|
> XBYas|XBYas.zip|http://fonts.irmug.com/Yas.zip|"XBYas From irmug.com"|
> XBZiba|XBZiba.zip|http://fonts.irmug.com/Ziba.zip|"XBZiba From irmug.com"|
> Tahoma|Tahoma.zip|http://fzerorubigd.github.com/persian-fonts-linux/tahoma.zip|"MS Tahoma, just here to completet the set :)"|
> Samim|Samim.zip|https://github.com/rastikerdar/samim-font/archive/master.zip|"A Persian (Farsi) Font"|
> Shabnam|Shabnam.zip|https://github.com/rastikerdar/shabnam-font/archive/master.zip|"A Persian (Farsi) Font"|
> Sahel|Sahel.zip|https://github.com/rastikerdar/sahel-font/archive/master.zip|"A Persian (farsi) Font"|
> VazirCode|VazirCode.zip|https://github.com/rastikerdar/vazir-code-font/archive/master.zip|"A Persian (farsi) Monospaced Font for coding"|
> Tanha|Tanha.zip|https://github.com/rastikerdar/tanha-font/archive/master.zip|"Tanha, A Persian (Farsi) font"|
> Nahid|Nahid.zip|https://github.com/rastikerdar/nahid-font/archive/master.zip|"Nahid, A Persian (Farsi) font"|
> Parastoo|Tarastoo.zip|https://github.com/rastikerdar/parastoo-font/archive/master.zip|"Parastoo, A Persian (Farsi) font"|
> RFonts|RFonts.zip|https://virastaran.net/wp-content/uploads/2014/01/IRFontPack-virastaran.net_.zip|"Fonts from I.R. Iran Supreme Council of Information and Communication Technology (SCICT)"|
> ```

`[sajjad@fedora ~]$ curl http://fzero.rubi.gd/persian-fonts-linux/list
Vazir|Vazir.zip|https://github.com/rastikerdar/vazir-font/archive/master.zip|"A Persian (Farsi) Font"|
FarsiFonts|FarsiFonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/farsifonts-0.4.zip|"Full standard fonts from farsiweb.ir(RIP) including Elham, Terafik, Terafik Bold, Titr, Roya, Roya Bold, Koodak, Nazli, Nazli Bold, and Homa"|
BFonts|bfonts.zip|http://fzerorubigd.github.com/persian-fonts-linux/bfonts.zip|"Old school B Fonts, Originally published with Borna Rayaneh products in early 2000."|
IranianSans|irsans.zip|http://fzerorubigd.github.com/persian-fonts-linux/irsans.zip|"Iranian Sans"|
IranNastaliq|in.zip|http://fzerorubigd.github.com/persian-fonts-linux/irannastaliq.zip|"Iran nastaliq font"|
FPF|FPF.zip|http://fzerorubigd.github.com/persian-fonts-linux/fpf-1.0.0-Beta-1.zip|"Free Persian Font, Originally from source forge."|
Lalezar|Lalezar-Regular.ttf|https://github.com/BornaIz/Lalezar/raw/master/Font%20files/Lalezar-Regular.ttf|"Lalezar font"|
XBZar|XBZar.zip|http://fonts.irmug.com/Zar.zip|"XBZar From irmug.com"|
XBNilufar|XBNilufar.zip|http://fonts.irmug.com/Niloofar.zip|"XBNilufar From irmug.com"|
XBKhoramshahr|XBKhoramshahr.zip|http://fonts.irmug.com/Khoramshahr.zip|"XBKhoramshahr From irmug.com"|
XBKayhan|XBKayhan.zip|http://fonts.irmug.com/Kayhan.zip|"XBKayhan From irmug.com"|
XBYaghout|XBYaghout.zip|http://fonts.irmug.com/Yagut.zip|"XBYaghout From irmug.com"|
XBRiyaz|XBRiyaz.zip|http://fonts.irmug.com/Riyaz.zip|"XBRiyaz From irmug.com"|
XBRoya|XBRoya.zip|http://fonts.irmug.com/Roya.zip|"XBRoya From irmug.com"|
XBShafigh|XBShafigh.zip|http://fonts.irmug.com/Shafigh.zip|"XBShafigh From irmug.com"|
XBShafighKurd|XBShafighKurd.zip|http://fonts.irmug.com/Shafigh%20Kurd.zip|"XBShafighKurd From irmug.com"|
XBShafighUzbek|XBShafighUzbek.zip|http://fonts.irmug.com/Shafigh%20Uzbek.zip|"XBShafighUzbek From irmug.com"|
XBShiraz|XBShiraz.zip|http://fonts.irmug.com/Shiraz.zip|"XBShiraz From irmug.com"|
XBSols|XBSols.zip|http://fonts.irmug.com/Sols.zip|"XBSols From irmug.com"|
XBTitr|XBTitr.zip|http://fonts.irmug.com/Titre.zip|"XBTitr From irmug.com"|
XBTabriz|XBTabriz.zip|http://fonts.irmug.com/Tabriz.zip|"XBTabriz From irmug.com"|
XBTraffic|XBTraffic.zip|http://fonts.irmug.com/Traffic.zip|"XBTraffic From irmug.com"|
XBVahid|XBVahid.zip|http://fonts.irmug.com/Vahid.zip|"XBVahid From irmug.com"|
XBVosta|XBVosta.zip|http://fonts.irmug.com/Vosta.zip|"XBVosta From irmug.com"|
XBYermook|XBYermook.zip|http://fonts.irmug.com/Yermook.zip|"XBYermook From irmug.com"|
XBYas|XBYas.zip|http://fonts.irmug.com/Yas.zip|"XBYas From irmug.com"|
XBZiba|XBZiba.zip|http://fonts.irmug.com/Ziba.zip|"XBZiba From irmug.com"|
Tahoma|Tahoma.zip|http://fzerorubigd.github.com/persian-fonts-linux/tahoma.zip|"MS Tahoma, just here to completet the set :)"|
Samim|Samim.zip|https://github.com/rastikerdar/samim-font/archive/master.zip|"A Persian (Farsi) Font"|
Shabnam|Shabnam.zip|https://github.com/rastikerdar/shabnam-font/archive/master.zip|"A Persian (Farsi) Font"|
Sahel|Sahel.zip|https://github.com/rastikerdar/sahel-font/archive/master.zip|"A Persian (farsi) Font"|
VazirCode|VazirCode.zip|https://github.com/rastikerdar/vazir-code-font/archive/master.zip|"A Persian (farsi) Monospaced Font for coding"|
Tanha|Tanha.zip|https://github.com/rastikerdar/tanha-font/archive/master.zip|"Tanha, A Persian (Farsi) font"|
Nahid|Nahid.zip|https://github.com/rastikerdar/nahid-font/archive/master.zip|"Nahid, A Persian (Farsi) font"|
Parastoo|Tarastoo.zip|https://github.com/rastikerdar/parastoo-font/archive/master.zip|"Parastoo, A Persian (Farsi) font"|
RFonts|RFonts.zip|https://virastaran.net/wp-content/uploads/2014/01/IRFontPack-virastaran.net_.zip|"Fonts from I.R. Iran Supreme Council of Information and Communication Technology (SCICT)"|
[sajjad@fedora ~]$ 
`

**Comment by fzerorubigd** [comment]
sorry, I missed this repository altogether :) I fixed the URL now
